### ISSUE TITLE
[BUG]: address wildcard list performance

### ISSUE THREAD

**Issue by wranders** [wranders/coredns-filter#10]
### Bug Description / What Happened

Each entry in wildcard lists are currently loaded as a regular expression. With large lists, this is resulting in essentially a self-imposed Denial of Service (DoS) situation where every request is being checked and pegging CPU usage, causing clients to perceive DNS services to be unavailable.

The current RegEx for each wildcard entry is as follows:

https://github.com/wranders/coredns-filter/blob/0f142c8cd0709d65244366c527f1f1f69575e445/action.go#L166

This could be _can_ be slightly optimized to:

```regex
(^|\\.)%s
```

but would still probably result in the same problem.

**_Another solution must be explored._**

Perhaps unifying the disparate slices into a trie where wildcards could be identified as a dedicated field. Reversing domains such as `com.example.*` and returning a block result if a node contains a `block` field. This would incur a drastically higher memory footprint, but that seems preferable to a situation where CPU usage renders the entire DNS server unresponsive.

Another potential solution would be to just run `HasSuffix` for wildcard entries, though I don't know how this would compare to current CPU usage.

Example:

```go
if strings.HasSuffix(request, ".example.com" {
    # Block request
}
```

### Expected Behavior

Responsive DNS services with large block lists

### Steps to reproduce

1. Use a large wildcard blocklist
2. ???
3. lose DNS services

### Additional Info

The `v0.2.4` release has functional RegEx/wildcard support, but should only be used with very small lists.

### OS

Raspberry Pi OS 11, Linux 5.10.103-v7l, armv7l

### Version

v0.2.4

### Logs

```
Sep 24 23:12:56 dns1 coredns[18610]: [ERROR] plugin/errors: 2 settings-win.data.microsoft.com. A: EOF
Sep 24 23:12:56 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
Sep 24 23:12:56 dns1 coredns[18610]: [ERROR] plugin/errors: 2 www.gstatic.com. A: EOF
Sep 24 23:12:57 dns1 coredns[18610]: [ERROR] plugin/errors: 2 updates.coreos.fedoraproject.org. AAAA: EOF
Sep 24 23:12:57 dns1 coredns[18610]: [ERROR] plugin/errors: 2 www.gstatic.com. A: EOF
Sep 24 23:12:57 dns1 coredns[18610]: [ERROR] plugin/errors: 2 unagi-na.amazon.com. A: EOF
Sep 24 23:12:58 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
Sep 24 23:12:59 dns1 coredns[18610]: [ERROR] plugin/errors: 2 unagi-na.amazon.com. AAAA: EOF
Sep 24 23:13:01 dns1 coredns[18610]: [ERROR] plugin/errors: 2 unagi-na.amazon.com. AAAA: EOF
Sep 24 23:13:02 dns1 coredns[18610]: [ERROR] plugin/errors: 2 updates.coreos.fedoraproject.org. A: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 ab992t7ewg8z.na.api.amazonvideo.com. A: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 unagi-na.amazon.com. AAAA: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 clients4.google.com. HTTPS: EOF
Sep 24 23:13:03 dns1 coredns[18610]: [ERROR] plugin/errors: 2 unagi-na.amazon.com. AAAA: EOF
Sep 24 23:13:04 dns1 coredns[18610]: [ERROR] plugin/errors: 2 connectivitycheck.gstatic.com. A: EOF
```

and so on, due to inability to respond to requests.

**Comment by bcookatpcsd** [comment]
Just found this.. 

Looks great.. "I love what you have done with the place.." 

I have almost 10k chromebooks that I do recursion for.. and have an 'adblock syntax' list of almost 5k domains

Have you seen this project? 

0xERR0R/blocky

The logging in coredns is better for what I am doing.. 

I presently use the forward plugin and an import of: 

except lan lan1 home myfiosgateway mynetworksettings.com discord.gg etc..

you get a million of these:

```
[ERROR] plugin/errors: 2 wpad.lan. AAAA: plugin/forward: no next plugin found
[ERROR] plugin/errors: 2 wpad.lan. A: plugin/forward: no next plugin found
[ERROR] plugin/errors: 2 wpad.lan. HTTPS: plugin/forward: no next plugin found
```

Definitely would help test..
